[package]
name = "automatic_file_sorter"
version = "1.3.0"
edition = "2021"
authors = ["Xanthus58 <Xanthus58@protonmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"