on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

name: Cargo-Doc

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --target-dir docs 
  commit_and_push:
    name: Push Commit
    runs-on: ubuntu-latest
    steps:
      uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        commit_message: Automated Doc Update
  