# A custom github action for all of the core jobs i want done across all of my repos
# Made by @Xanthus58

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support.

name: Rust-Core-Utils

on:
  push:
    branches: [ "*" ]
  pull_request:
    types: [opened, reopened]
  
jobs:
# Ensure the application can be built and run successfully
  build:
    name: Rust-Core-Utils
    runs-on: ubuntu-latest
    steps:
    - uses: Xanthus58/rust-core@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}